[package]
name = "bft_interp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bft_types = { path = "../bft_types" }
rstest = "0.18.2"
tempfile = "3.10.0"
